#!/usr/bin/env bash
echo "This is the git add command."

# The command's name
echo -e 'git add'

# the command's description
echo "The git add command is executed when you are ready to create a snapshot out of the changes you’ve made. The snapshot goes to the staging area before being committed. Git add is the step before git commit. "

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git add [ -v | -i]"
echo -e "\t-v: print added files"
echo -e "\t-i: add files interactively"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git add myfile"
echo "Adds 'myfile' to the index. Once added to the index, myfile will be included in the next commit."

# example 2
echo "git add ."
echo "The git add command works with standard regular expression syntax. So using the . operator (wildcard), will add all files in the current git context to the index (the * wildcard will also work). Files that have been modified or are new need to be added to the index to be included in the commit."


exit 0
