#!/usr/bin/env bash
echo "This is a git test command."

# The command's name
echo -e 'git test'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git add myfile"
echo "Adds 'myfile' to the index. Once added to the index, myfile will be included in the next commit."

# example 2
echo "git add ."
echo "The git add command works with standard regular expression syntax. So using the . operator (wildcard), will add all files in the current git context to the index (the * wildcard will also work). Files that have been modified or are new need to be added to the index to be included in the commit."


exit 0
