#!/usr/bin/env bash
echo "This is the git checkout command."

# The command's name
echo -e 'git checkout'

# the command's description
echo "The checkout command is used to switch between branches and can also be used to restore delete files. Combined with flags the checkout command can perform multiple tasks such as create or merge branches with a single command.. "

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git checkout master"
echo "Return to the master branch"

# example 2
echo "git checkout a1e8fb5 hello.js"
echo "Checkout hello.js to a1e8fb5 commit and adds it to the staging area"


exit 0
