#!/usr/bin/env bash
echo "This is the git rm command."

# The command's name
echo -e 'git commit'

# the command's description
echo "The git commit command is used to submit staged changes to the git origin repository. Staged changes are the way git keeps related modifications in one snap shot. Git commit is used to tell git you are ready to submit the staged changes to the origin repository."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git test"
echo description here

# example 2
echo "git test something"
echo description here


exit 0
