#!/usr/bin/env bash
echo "This is a git diff command."

# The command's name
echo -e 'git diff'

# the command's description
echo "Show changes. It can be used to compare commits, branches or working trees. Most common use is to show changes between the actual staging area and last commit."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git test"
echo description here

# example 2
echo "git test something"
echo description here


exit 0
