#!/usr/bin/env bash
echo "This is the git fetch command."

# The command's name
echo -e 'git fetch'

# the command's description
echo "Retreives branches and/or tags (refs) from another repository. By default, git fetch retrieves from the origin remote. Another remote or group of remotes can be specified if origin isn't the desired remote. Unlike git pull, this command only downloads the refs, it doesn't merge them in anyway."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git test"
echo description here

# example 2
echo "git test something"
echo description here


exit 0
