#!/usr/bin/env bash
echo "This is the find command."

# The command's name
echo -e 'find'

# the command's description
echo "The find command allows a user to search for files that match a certain criteria within a directory. Users can search for a specific file name using wildcard parameters. Users can also find files that are a certain size. Also, find can be used to select only files of a specific type or extension."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
