#!/usr/bin/env bash
echo "This is a git test command."

# The command's name
echo -e 'git test'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git init [ --bare | -q ]"
echo -e "\t--bare: This creates a bare repository with no branches (including master). Useful when creating a central repository."
echo -e "\t-q: This is the quiet setting. Only error and warning messages will be displayed, all other output is suppressed."
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git test"
echo description here

# example 2
echo "git test something"
echo description here


exit 0
