#!/usr/bin/env bash
echo "This is a git test command."

# The command's name
echo -e 'git test'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git log"
echo "Displays a log of all the commits to the current branch. Commits are listed in chronological order (default). If the output takes up more than a single screen, you can use <space> to scroll. 'q' will exit the listing."

# example 2
echo "git log -n9 --oneline"
echo "The git log command displays a lot of data with its default formatting. This example will display the last 9 commits with each commit condensed to a simple one line format. 


iexit 0
