#!/usr/bin/env bash
echo "This is the git log command."

# The command's name
echo -e 'git log'

# the command's description
echo "The git log command is executed when you want to view the project history. Git log lets you view the list of previously committed snapshots and even filter it or search for changes. "

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git log [ --pretty=format:'...' | --graph | --date=<format> ]"
echo -e "\t--pretty=format:'...': defines the format of the output."
echo -e "\t--graph: display commit tree with ASCII charachters"
echo -e "\t--date=<format>: set the date format. Usually to \'short\'"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git log"
echo "Displays a log of all the commits to the current branch. Commits are listed in chronological order (default). If the output takes up more than a single screen, you can use <space> to scroll. 'q' will exit the listing."

# example 2
echo "git log -n9 --oneline"
echo "The git log command displays a lot of data with its default formatting. This example will display the last 9 commits with each commit condensed to a simple one line format." 


exit 0
