#!/usr/bin/env bash
echo "This is the git merge command."

# The command's name
echo -e 'git merge'

# the command's description
echo "The git merge command is used to resolve the changes between branches. Git merge will unify the project history back into a single repository."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git merge [ -m <msg> | --abort]"
echo -e "\t-m: <msg>: Set the message for the merge commit (if created)"
echo -e "\t--abort: Abort the reolution of merge conflits and try to go backwards to pre-merge state"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git merge feature-branch"
echo "In this, git merge's most simple usage example, it will attempt to merge feature-branch with the currently checked out branch. For example, if this command was run while the master branch was checkout out git would attempt to merge feature-branch into master."

# example 2
echo "git merge --abort"
echo "Aborts the merge. Sometimes merge's don't work out. When a merge fails due to a conflict, you need to resolve that conflict before the merge can take place. If you are unsure of how to resolve the conflict, you can always backout of the merge completly using the --abort flag."


exit 0
