#!/usr/bin/env bash
echo "This is a git test command."

# The command's name
echo -e 'git test'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git merge feature-branch"
echo "In this, git merge's most simple usage example, it will attempt to merge feature-branch with the currently checked out branch. For example, if this command was run while the master branch was checkout out git would attempt to merge feature-branch into master."

# example 2
echo "git merge --abort"
echo "Aborts the merge. Sometimes merge's don't work out. When a merge fails due to a conflict, you need to resolve that conflict before the merge can take place. If you are unsure of how to resolve the conflict, you can always backout of the merge completly using the --abort flag."


exit 0
