#!/usr/bin/env bash
echo "This is the git pull command."

# The command's name
echo -e 'git pull'

# the command's description
echo "The git pull command will fetch from the remote repository and integrate it into the local branch. This command is a compound or short-hand command. When you issue a git pull command, git first runs a git fetch, followed by a git merge, merging the FETCH_HEAD into the local branch. You can modify the actions using various flags, such as whether to commit or not, or changing the merge to a rebase."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git test"
echo description here

# example 2
echo "git test something"
echo description here


exit 0
