#!/usr/bin/env bash
echo "This is the git rebase command."

# The command's name
echo -e 'git rebase'

# the command's description
echo "Git rebase is an alternative to merging branches. In a merge, changes from a branch are resolved into the master head. In a rebase, a branch is attached to the front of the master head. In a way, it overwrites the master head with the branch that is being rebased. This is an acceptable way to incorporate a new feature."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git rebase master"
echo "After checking out the branch to rebase, the example command will incorporate the changes from master onto the checked out branch. This has a similar effect to a merge."

# example 2
echo "git rebase -i HEAD~3"
echo -e "Begins an interactive (-i) rebase using only the last 3 commits. From here you can choose how to handle each commit.\n
Your options are: \npick, p = keep the commit.
\nreword, r = keep the commit but change the commit message.
\nedit, e = use the commit, but stop for amending.
\nsquash, s = use commit but combine with previous commit.
\nfixup, f = same as squash, but loses the commit message.
\nexec, x = run the following command using shell.     "


exit 0
