#!/usr/bin/env bash
echo "This is the git reset command."

# The command's name
echo -e 'git reset'

# the command's description
echo "Used to reset the HEAD to a earlier, specified version. A reset is often used to 'undo' a git add. For example, a git reset <filename> is the opposite of git add <filename>. A reset, depending on the [<mode>] provided can change the working tree, the index or both."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git test"
echo description here

# example 2
echo "git test something"
echo description here


exit 0
