#!/usr/bin/env bash
echo "This is the git status command "

# The command's name
echo -e 'git status'

# the command's description
echo "Shows the status of the git working tree. When this command is entered in a local repository, it will show the status of the working tree. Any files that differ from the current HEAD will be diplayed as a path to that file. This includes files or directories that have been added, deleted, or modified. A number of flags are available to help fine-tune the output."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git status"
echo "Show the working tree status. This includes brach status, files to be commited and modified files"

# example 2
echo "git status -v"
echo "Show the working tree status and the changes staged to be commited"


exit 0
