#!/usr/bin/env bash
echo "This is the chmod command."

# The command's name
echo -e 'chmod'

# the command's description
echo "Sort for change mode. This command is used to change file permissions.
Permissions are read (r), write (w) and execute (x), which can be granted or removed to the file owner(u), users in the file's group(g), other users (o) or all users (a).
Mode can be represented by the previous symbols or by three octal numbers corresponding to the three user types (ugo)."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
