#!/usr/bin/env bash
echo "This is the clear command."

# The command's name
echo -e 'clear'

# the command's description
echo "The clear command will clear the screen along with the scroll-back buffer if possible. This command ignores any flags and parameters passed to it through the command line. Use this command when you want a fresh screen."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "clear"
echo "Clears your screen"

# example 2
echo "test something"
echo description here


exit 0
