#!/usr/bin/env bash
echo "This is the copy command."

# The command's name
echo -e 'cp'

# the command's description
echo "Copy files and directories to <destination>.
If <destination> is a directory, it copies all the source files and directories to the destination directory.
If <destination> has a filename, it copies the given file to the <destination>."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
