#!/usr/bin/env bash
echo "This is the exit fuction."

# The command's name
echo -e 'exit'

# the command's description
echo "The exit function is used to terminate a calling process inside a bash script. It is often followed by an integer between 0 and 255. The integer is a code that is used to communicate if the script completed successfully or not. Any code that is not 0 denotes an error."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
