#!/usr/bin/env bash
echo "This is a test command."

# The command's name
echo -e 'test'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "find /home -name myfile"
echo "This example will find a file or directory named (-name) 'myfile' in the '/home' directory."

# example 2
echo -e "find /home/music/ -type f -name \"*.wav\" -exec rm -f {} \\;"
echo "This usage will find all files (-type f) with the '.wav' (-name) extension and with the use of the -exec flag we can execute another command on each occurance. In this case we call the rm command and delete each one. "


exit 01
