#!/usr/bin/env bash
echo "This is the find command."

# The command's name
echo -e 'find'

# the command's description
echo "The find command allows a user to search for files that match a certain criteria within a directory. Users can search for a specific file name using wildcard parameters. Users can also find files that are a certain size. Also, find can be used to select only files of a specific type or extension."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "find <path> [ -type c | -name pattern | -exec command ]"
echo -e "\t-type: find files of type c"
echo -e "\t-name: find files with base name matching pattern"
echo -e "\t-exec: execute command for every match"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "find /home -name myfile"
echo "This example will find a file or directory named (-name) 'myfile' in the '/home' directory."

# example 2
echo -e "find /home/music/ -type f -name \"*.wav\" -exec rm -f {} \\;"
echo "This usage will find all files (-type f) with the '.wav' (-name) extension and with the use of the -exec flag we can execute another command on each occurance. In this case we call the rm command and delete each one. "


exit 0
