#!/usr/bin/env bash
echo "This is man command."

# The command's name
echo -e 'man'

# the command's description
echo "Man (short for manual) is used to view a command manual. Manuals are generally split into sections, accesible by number(1-8). By default, man uses a terminal pager such as \"more\" or \"less\"."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
