#!/usr/bin/env bash
echo "This is a mkdir command."

# The command's name
echo -e 'mkdir'

# the command's description
echo "The mkdir command is used to create a new directory. The name of the new directory must not exist already. The new directory name must be unique."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "mkdir mydir"
echo "Creates a directory in the current working directory called mydir."

# example 2
echo "mkdir -pv ~/mydira/mydirb/mydirc"
echo "Creates the following directories including parent (-p) directories, as needed, and prints a message (-v) for each directory created."


exit 0
