#!/usr/bin/env bash
echo "This is a test command."

# The command's name
echo -e 'test'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "more [ -d | -<num> ]"
echo -e "\t-d: If the user presses an illegal key while using more this flag causes more to display the message '[Press space to continue, q to 'quit' ' instead of an alert sound."
echo -e "\t-<num>: Sets the number of lines to display per page."
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
