#!/usr/bin/env bash
echo "This is mv command."

# The command's name
echo -e 'mv'

# the command's description
echo "Move files to <destination>. If <destination> is a directory, it moves the files to that directory.
If a filename is provided as <destination>, it renames the file to the filename provided.
Both behaviour can be combined to move a file to a directory and rename it."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "mv [ --suffix, -S | -u ]"
echo -e "\t--suffix, -S: Creates a backup of the destination before overwriting it. Used when you want to replace file1 with file2 but keep a copy of file2. This flag adds the supplied suffix to the original filename."
echo -e "\t-u: Moves only the files that do not exist in the destination directory. Useful when moving files using wildcards."
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
