#!/usr/bin/env bash
echo "This is a test command."

# The command's name
echo -e 'test'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "mv [ --suffix, -S | -u ]"
echo -e "\t--suffix, -S: Creates a backup of the destination before overwriting it. Used when you want to replace file1 with file2 but keep a copy of file2. This flag adds the supplied suffix to the original filename."
echo -e "\t-u: Moves only the files that do not exist in the destination directory. Useful when moving files using wildcards."
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
