#!/usr/bin/env bash
echo "This is the ping command."

# The command's name
echo -e 'ping'

# the command's description
echo "The ping command is used to determine if a computer with a specified IP address is accessable. This command is part of the TCP/IP set of protocols. The ping command sends data packets (ICMP) to the supplied IP address. If the computer system at the other end is 'listening' (and is configured to repond to ping requests) it will answer back. The sending computer will be able to determine how long it took for the packet to reach the computer and recieve the response as well as how many hops it took to get there."

echo "This is one of the most useful tools for networking and network troubleshooting. There are a number of useful flags to fine-tune the command to your needs."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
