#!/usr/bin/env bash
echo "This is a pipe command."

# The command's name
echo -e 'pipe'

# the command's description
echo "The pipe command is entered using the | symbol on the keyboard. It directs the output of a process to the specified location such as a file. It can even output to another command. "

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git test"
echo description here

# example 2
echo "git test something"
echo description here


exit 0
