#!/usr/bin/env bash
echo "This is a test command."

# The command's name
echo -e 'test'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "rm myfile"
echo "removes myfile from the current working directory. If the file is write protected (no w permission) a prompt to confirm will be given."

# example 2
echo "rm -rf *"
echo "Arguably, the most dangerous command in Linux. This command will delete all files and directories in the current working directory as well as all sub-directories (-r) without prompts and forcing (-f) the deletion. Remember there is no Recycle Bin in command line. 


exit 0
