#!/usr/bin/env bash
echo "This is a rm command."

# The command's name
echo -e 'rm'

# the command's description
echo "The rm command is used to remove a file or directory. Removing a directory is not the default functionality of this command. The –r (recursive) flag is required to remove directories."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "rm [ -i | -f | -r ] FILE"
echo -e "\t-i: ask for confirmation before each deletion"
echo -e "\t-f: forces the deletion without asking for confirmation"
echo -e "\t-r: remove directories and their contents recursively"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "rm myfile"
echo "removes myfile from the current working directory. If the file is write protected (no w permission) a prompt to confirm will be given."

# example 2
echo "rm -rf *"
echo "Arguably, the most dangerous command in Linux. This command will delete all files and directories in the current working directory as well as all sub-directories (-r) without prompts and forcing (-f) the deletion. Remember there is no Recycle Bin in command line."


exit 0
