#!/usr/bin/env bash
echo "This is the ssh command."

# The command's name
echo -e 'ssh'

# the command's description
echo "The ssh command is the OpenSSH SSH client for Bash. SSH (secure socket host) is a program that allows a connection to another computer (SSH Host) through a secure connection using SSH protocols. It supports IP4 and IP6 addrressing as well as many of the top encryption alogrithims like AES and  Blowfish. Support for authentication methods such as host based and public key authentiction are also built in and configurable."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
