#!/usr/bin/env bash
echo "This is a sudo command."

# The command's name
echo -e 'sudo'

# the command's description
echo "The sudo command allows one user to execute a command as if they were logged in as another user. The ability to use sudo is determined by the security policy. The security policy must grant the user rights to run the sudo command. Usually the security policy will dictate that the user enters a password before executing sudo."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git test"
echo description here

# example 2
echo "git test something"
echo description here


exit 0
