#!/usr/bin/env bash
echo "This is the touch command."

# The command's name
echo -e 'touch'

# the command's description
echo "The touch command is an easy way to create new, empty files. Touch is also used to changed the timestamps on existing files, without modifying the contents. The file's timestamp would change to the date and time the file was 'touched'."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
