#!/usr/bin/env bash
echo "This is the touch command."

# The command's name
echo -e 'touch'

# the command's description
echo "The touch command is an easy way to create new, empty files. Touch is also used to changed the timestamps on existing files, without modifying the contents. The file's timestamp would change to the date and time the file was 'touched'."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "touch touchedFile"
echo "Create a new empty file called \"touchedFile\""

echo
# example 2
echo "touch -t 201603011230.45 touchedFile"
echo "Update the access and modification times of \"touchedFile\" to March 01, 2016 at 12:30:45"


exit 0
