#!/usr/bin/env bash
echo "This is about variables."

# The command's name
echo -e 'bash variables'

# the command's description
echo "Bash variables are similar to variables in any programming language. In bash, they are not strongly typed. They can contain a number, character, or a string of characters. Variables in bash do not need to be declared. To assign a value to a variable simply declare it. For example let x=1."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git test"
echo description here

# example 2
echo "git test something"
echo description here


exit 0
