#!/usr/bin/env bash
echo "This is a  wc command."

# The command's name
echo -e ' wc'

# the command's description
echo "The wc command is short for wordcount. The wc command takes the argument of a file name and and is able to provide information on the file related to the number of lines, the number of words, or the amount of bytes in the file. "

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "wc myfile"
echo "Prints out the number of lines, word count and byte count in myfile."

# example 2
echo "wc -mw myfile"
echo "Prints out the number of characters (-m) and the number of words (-w) in myfile."


exit 0
