#!/usr/bin/env bash
echo "This is the whoami command."

# The command's name
echo -e 'whoami'

# the command's description
echo "The whoami command prints the name of the user logged into the current shell. Often used to determine who the current user is."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "whoami"
echo "Print the current user."


exit 0
